hebi:
  log: storage/hebi.log
  nyaa:
    category:
      - 1_37
    page-path: '/media/INTENSO/pages/%d.html'
    torrent-path: '/media/INTENSO/torrents/%d.torrent'
    status-file: '/home/eater/projects/hebi-neko/status.json'